wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.14.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681011600.726799
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.7
      5: 0.14.1
      8:
      - 1
      - 5
